---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    networks:
      - qbittorrent-network
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ} # Use your machine's current time zone for the container's logs
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /path/to/qbittorrent/appdata:/config
      - /path/to/downloads:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
  qbittorrent-ban-torrentstorm:
    image: ghcr.io/rcunov/qbittorrent-ban-torrentstorm:latest
    networks:
      - qbittorrent-network
    init: true # https://docs.docker.com/compose/compose-file/compose-file-v3/#init
    environment:
      # - logLevel=0 # 0=DEBUG, 1=INFO, 2=ERROR. Uncomment this if you want more verbose logs. Defaults to 1
      # - sleepTime=2 # Defaults to 10 seconds between checks
      - qbUrl=http://qbittorrent:8080 # Defaults to http://localhost:8080
      - qbUsername=${qbUsername} # qBittorrent web UI username
      - qbPassword=${qbPassword} # qBittorrent web UI password
      - TZ=${TZ} # Use your machine's current time zone for the container's logs

networks:
  qbittorrent-network:
